name: Build container
on:
  push:
    paths:
      - 'generator/**'
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "generator"
          push: true
          tags: 'ghcr.io/edinburghhacklab/hacklab-training:${{ github.ref_name }}'
