# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: hacklab-training

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - uses: actions/checkout@v2
        with:
          repository: edinburghhacklab/hacklab-training-generator
          path: hacklab-training-generator

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python3-jinja2 python3-mistune texlive-base texlive-latex-extra texlive-fonts-recommended 

      - name: Build
        run: |
          # unshallow so we can see last commit of each file
          cd hacklab-training
          git fetch --unshallow
          cd ..
          # build the PDFs
          cd hacklab-training-generator
          ./generate.py ../hacklab-training ../gh-pages
          cd ..
          # commit to gh-pages branch
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.html
          git add **/*.pdf
          git commit -m "generated"
          git push
